### ISSUE TITLE
composer install in error "  conflict with your requirements or minimum-stability "

### ISSUE THREAD

**Issue by nephaste** [nabab/appui-cron#1]
trying to build with a composer install (php 7.3.11)

but kicked on error

but these conflict with your requirements or minimum-stability

adding to composer.json

...
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

fixed download issue

**Comment by nabab** [comment]
Hi,

Thanks for your interest but this is a plugin for an application we have not released yet.

None of the packages starting with appui are usable.
